#!/bin/bash
set -e

apt update -y
apt install unzip -y

# Install AWS CLI v2
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
./aws/install

# Download kubectl
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

# Download kops
wget https://github.com/kubernetes/kops/releases/download/v1.33.0/kops-linux-amd64

chmod +x kubectl kops-linux-amd64

mv kubectl /usr/local/bin/kubectl
mv kops-linux-amd64 /usr/local/bin/kops

# Create S3 bucket
aws s3api create-bucket \
  --bucket kailash9696.k8s.local \
  --region ap-south-1 \
  --create-bucket-configuration LocationConstraint=ap-south-1

# Enable versioning
aws s3api put-bucket-versioning \
  --bucket kailash9696.k8s.local \
  --versioning-configuration Status=Enabled

export KOPS_STATE_STORE=s3://kailash9696.k8s.local

# Create cluster (let kops choose AMI)
kops create cluster \
  --name kailash.k8s.local \
  --zones ap-south-1a \
  --control-plane-count=1 \
  --control-plane-size t3.medium \
  --node-count=2 \
  --node-size t3.micro

kops update cluster --name kailash.k8s.local --yes --admin
